In [1]:

import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv('customer.csv')

In [3]:
df.sample(5)

age  gender   review education purchased
17   22  Female     Poor        UG       Yes
29   83  Female  Average        UG       Yes
34   86    Male  Average    School        No
1    68  Female     Poor        UG        No
31   22  Female     Poor    School       Yes

In [4]:
df = df.iloc[:,2:]

In [5]:
df.head()

review education purchased
0  Average    School        No
1     Poor        UG        No
2     Good        PG        No
3     Good        PG        No
4  Average        UG        No

In [6]:
from sklearn.preprocessing import OrdinalEncoder

In [8]:
from sklearn.model_selection import train_test_split



X_train, X_test, y_train, y_test = train_test_split(df.iloc[:,0:2], df.iloc[:,-1], test_size=0.2)

In [9]:
X_train

review education
11     Good        UG
48     Good        UG
0   Average    School
13  Average    School
39     Poor        PG
18     Good    School
22     Poor        PG
14     Poor        PG
9      Good        UG
5   Average    School
46     Poor        PG
43     Poor        PG
26     Poor        PG
42     Good        PG
36     Good        UG
10     Good        UG
32  Average        UG
45     Poor        PG
4   Average        UG
29  Average        UG
7      Poor    School
2      Good        PG
49     Good        UG
31     Poor    School
16     Poor        UG
44  Average        UG
6      Good    School
47     Good        PG
41     Good        PG
23     Good    School
21  Average        PG
34  Average    School
20  Average    School
19     Poor        PG
24  Average        PG
12     Poor    School
40     Good    School
1      Poor        UG
28     Poor    School
33     Good        PG

In [10]:
oe = OrdinalEncoder(categories=[['Poor','Average','Good'],['School','UG','PG']])

In [11]:

oe.fit(X_train)

OrdinalEncoder(categories=[['Poor', 'Average', 'Good'], ['School', 'UG', 'PG']])

In [12]:
X_train = oe.transform(X_train)

In [13]:

X_train

array([[2., 1.],
       [2., 1.],
       [1., 0.],
       [1., 0.],
       [0., 2.],
       [2., 0.],
       [0., 2.],
       [0., 2.],
       [2., 1.],
       [1., 0.],
       [0., 2.],
       [0., 2.],
       [0., 2.],
       [2., 2.],
       [2., 1.],
       [2., 1.],
       [1., 1.],
       [0., 2.],
       [1., 1.],
       [1., 1.],
       [0., 0.],
       [2., 2.],
       [2., 1.],
       [0., 0.],
       [0., 1.],
       [1., 1.],
       [2., 0.],
       [2., 2.],
       [2., 2.],
       [2., 0.],
       [1., 2.],
       [1., 0.],
       [1., 0.],
       [0., 2.],
       [1., 2.],
       [0., 0.],
       [2., 0.],
       [0., 1.],
       [0., 0.],
       [2., 2.]])

In [14]:
oe.categories_

[array(['Poor', 'Average', 'Good'], dtype=object),
 array(['School', 'UG', 'PG'], dtype=object)]

In [15]:

X_train

array([[2., 1.],
       [2., 1.],
       [1., 0.],
       [1., 0.],
       [0., 2.],
       [2., 0.],
       [0., 2.],
       [0., 2.],
       [2., 1.],
       [1., 0.],
       [0., 2.],
       [0., 2.],
       [0., 2.],
       [2., 2.],
       [2., 1.],
       [2., 1.],
       [1., 1.],
       [0., 2.],
       [1., 1.],
       [1., 1.],
       [0., 0.],
       [2., 2.],
       [2., 1.],
       [0., 0.],
       [0., 1.],
       [1., 1.],
       [2., 0.],
       [2., 2.],
       [2., 2.],
       [2., 0.],
       [1., 2.],
       [1., 0.],
       [1., 0.],
       [0., 2.],
       [1., 2.],
       [0., 0.],
       [2., 0.],
       [0., 1.],
       [0., 0.],
       [2., 2.]])

In [16]:
from sklearn.preprocessing import LabelEncoder

In [17]:
le = LabelEncoder()

In [18]:

le.fit(y_train)

LabelEncoder()

In [19]:
le.classes_

array(['No', 'Yes'], dtype=object)

In [20]:
y_train = le.transform(y_train)
y_test = le.transform(y_test)

In [21]:

y_train

array([1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0,
       0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1])